---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-manager
spec:
  replicas: 1
  selector:
    app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: prabhuinbarajan/kafka-manager
        ports:
        - containerPort: 9000
        env:
        - name: ZK_HOSTS
          value: zoo1:2181,zoo2:2181,zoo3:2181
        - name: APPLICATION_SECRET
          value: letmein

