---
apiVersion: v1
kind: Service
metadata:
  name: kafka-manager-service
  labels:
    app: kafka-manager
spec:
  ports:
  - port: 9000
    name: kafka-manager-port
    targetPort: 9000
    protocol: TCP
  selector:
    app: kafka-manager
  type: LoadBalancer

